baseURL: "https://amanda-basso.github.io/"
languageCode: "en-us"
title: "Amanda Basso"

theme: "hyde"

params:
  description: "Let's talk about security, technology, psychology, books, and cats"

menus:
  main:
    - name: "Github"
      URL: "https://github.com/amanda-basso"
    - name: "LinkedIn"
      URL: "https://www.linkedin.com/in/amanda-basso-de-oliveira/"
    - name: "Lattes"
      URL: "http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K2715239U6"
