baseURL: "https://amanda-basso.github.com/"
languageCode: "en-us"
title: "Amanda Basso"

theme: "hyde"

params:
  description: "just another crypto, travelling, cats blog"

menus:
  main:
    - name: "Github"
      URL: "https://github.com/amanda-basso"
    - name: "LinkedIn"
      URL: "https://www.linkedin.com/in/amanda-basso-de-oliveira-335312182/"
    - name: "Lattes"
      URL: "http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K2715239U6"
