name: Deploy Hugo Blog to GitHub Pages

on:
  push:
    branches: [ main ] # Dispara o workflow quando houver alterações na branch main
  workflow_dispatch: # Permite execução manual do workflow

jobs:
  build:
    runs-on: ubuntu-latest # Atualizado para a versão mais recente do runner

    steps:
      # 1. Checkout do código
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true # Inclui submódulos (se aplicável)
          fetch-depth: 1 # Clona apenas o commit mais recente

      # 2. Setup Hugo (com versão estável especificada)
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.115.1' # Substitua pela versão que você precisa

      # 3. Build do site com Hugo
      - name: Build
        run: hugo --minify # Gera o site com otimização de arquivos

      # 4. Deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Usando o token padrão do GitHub
          #external_repository: amanda-basso/amanda-basso.github.io # Repositório de deploy
          publish_branch: gh-pages # Branch usada pelo GitHub Pages
          publish_dir: ./public # Diretório gerado pelo Hugo
